name: GitStats

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "profile/*.svg"

jobs:
  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate language stats
        uses: One-Simon/GitStats@main
        with:
          token: ${{ secrets.README_STATS_TOKEN }}
          username: One-Simon
